id: PE3C152EF
initial_creation_type: ocr
source_metadata:
  volumes:
    6e2a92f7452b41e68752ed2327768e64:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་བདུན་བརྒྱ་པ་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1682
      volume_number: 56
